id: IADA2F81B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T23:52:42+00:00'
last_modified: '2022-06-15T18:20:58.914846+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4593
  title: ནགས་ཀློང་ཁུ་བྱུག་འདུ་གནས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    43B0:
      image_group_id: I1PD28034
      title: Volume 1 of nags klong khu byug 'du gnas
      total_pages: 676
      order: 1
      base_file: 43B0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
